using Networking.HttpProtocol;
using Networking.HttpProtocol.ConnectWebApi;
using Networking.Main;

// Functions.EnunciationIPAddress();
// Functions.EnunciationIPEndpoint();
// Functions.WorkWithUri();
// Functions.GetHostEntry();
// Functions.GetHosAddresses();
// Functions.GetNetworkInterfaces();
// Functions.GetAllDevicesInNetwork();
// Functions.Monitoring();
// Functions.WorkWithSocket();
// Base.CreateHttpClient();
// await Base.SocketHttpClient();
// Base.CreateHttpClientWithIHttpClientFactory();
// Base.SendAsync();
// Base.SendGetAsync();
// Base.SendGetAsyncString();
// Base.SendGetAsyncByte();
// Base.SendGetAsyncStream();
// Base.SendGetAsyncJson();
// Base.SendGetAsyncJsonSecond();
// Base.SendGetAsyncJsonWithParametrs();
// Base.SendGetAsyncOfHeadLines();
// Base.SetupHeadLinesForRequest();
// Base.RecieveHeadLines();
// Base.RecieveHeadLinesOfTryValue();
// Base.SendTextRequest();
// Base.SendTextWithPostMethod();
// Base.SetupHeadLinesAndPostMethod();
// Base.SendJsonRequest();
// Base.SendPostAsJsonAsync();
// Base.SendFormAndFormUrlEncodedContent();
// Base.SendStreamAndArrayBytes();
// Base.SendStreamInByteArrayContent_String();
// Base.SendOneFileInMultipartFormDataContent();
// Base.SendManyFileUploads();
// Base.SendFileWithUserData();
// Base.RecieveCookiesOfSetCookie();
// Base.RecieveCookiesOfHttpClientHandler();
// Base.SendCookieOfHeader();
// Base.StartHttpServerOfResult();
// Base.RecieveInformationOfRequest();

// ServerApp.GetAllUser();
// ServerApp.GetUserById(3);
// ServerApp.DeleteUser(3);
// ServerApp.UpdateUser(new Person { Id = 4, Age = 332, Name = "TestUpdate" });
// ServerApp.GetAllUser();
Console.ReadKey();